# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  timeout: 5000

development:
  <<: *default
  database: captioned_development

test:
  <<: *default
  encoding: unicode
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: <%= ENV.fetch('DB_NAME', 'captioned_test') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
